#
# (C) Copyright 2018 Nexell
# Bongyu, KOO <freestyle@nexell.co.kr>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_PINCTRL_NEXELL) += pinctrl-nexell.o
obj-$(CONFIG_PINCTRL_NEXELL_NXP3220) += pinctrl-nxp3220.o
