#
# (C) Copyright 2017 Samsung
# Jaewon, Kim <jaewon02.kim@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y					+= boot_mode.o
obj-$(CONFIG_ARCH_SIP_S31NX)		+= mac.o
obj-$(CONFIG_ARTIK_OTA)			+= ota.o
obj-$(CONFIG_CMD_BMP)			+= bmp_logo.o
