#
# (C) Copyright 2018 Nexell
# JungHyun, Kim <jhkim@nexell.co.kr>
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y	:= board.o boot_mode.o
obj-$(CONFIG_ARCH_SIP_S31NX)	+= mac.o
obj-$(CONFIG_ARTIK_OTA)         += ota.o